apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  labels:
    app: django
    task: migrate
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: django_app:latest
          imagePullPolicy: Never
          command: ["python", "manage.py", "migrate", "--noinput"]
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: SECRET_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DATABASE_URL
            - name: DEBUG
              value: "False"
            - name: ALLOWED_HOSTS
              value: "127.0.0.1,localhost,192.168.49.2,star-burger.test"
